server:
  port: 8000
spring:
  redis:
    host: 202.115.16.208
    port: 8849
  datasource:
    url: jdbc:mysql://202.115.16.208:8850/demo
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: com.fan.demo.domain
  mapperLocations: com/fan/demo/dao/mappers/*.xml
